### ISSUE TITLE
paletter not compatible with Sass color functions?

### ISSUE THREAD

**Issue by bpernet** [meodai/paletter#2]
When calling paletter's `c()` function from within `lighten()` or `mix()`, I get the following error (I guess `darken()` and al. will raise the same).

```
Error: argument `$color` of `lighten($color, $amount)` must be a color

       Backtrace:
               ../common/src/components/button/scss/theme.button.scss:106, in function `lighten`
               ../common/src/components/button/scss/theme.button.scss:106
        on line 106 of ../common/src/components/button/scss/theme.button.scss
>>       background: lighten(c("interactive--active"), 50%),
```

**Comment by meodai** [comment]
The issue with this is that since the CLI tools outputs the colors with quotes, even if we unquote them, they are not recognized as colors anymore in sass. @HugoGiraudel wrote a 
set of tools to convert them back to proper colors: https://github.com/HugoGiraudel/SassyJSON/blob/master/stylesheets/decode/helpers/color/ But instead we should **not** output the quotes around the values in our CLI tool.

**Comment by meodai** [comment]
@bpernet make sure to use version 0.6.1 (I did just publish it to NPM)
